import { SidebarNav } from "@/sections/Sidebar/components/SidebarNav";

export const Sidebar = () => {
  return (
    <div className="fixed box-border caret-transparent grid [grid-template-areas:none] grid-cols-none grid-rows-none pointer-events-none inset-0 md:[grid-template-areas:'left_right'] md:grid-cols-[220px_1fr] md:grid-rows-[1fr]">
      <div className="box-content caret-black shrink col-end-auto col-start-auto row-end-auto row-start-auto min-h-0 min-w-0 pointer-events-auto text-wrap w-auto md:aspect-auto md:box-border md:caret-transparent md:shrink-0 md:col-end-[left] md:col-start-[left] md:row-end-[left] md:row-start-[left] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:w-[220px] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
        <div className="static bg-transparent box-content caret-black block flex-row grow-0 shrink h-auto text-wrap w-auto z-auto left-auto top-auto md:fixed md:aspect-auto md:bg-slate-800 md:box-border md:caret-transparent md:flex md:flex-col md:grow md:shrink-0 md:h-full md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:w-[220px] md:z-[1200] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:left-0 md:top-0">
          <div className="[align-items:normal] box-content caret-black block justify-normal min-h-0 min-w-0 text-wrap p-0 md:items-center md:aspect-auto md:box-border md:caret-transparent md:flex md:justify-start md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:px-4 md:py-[18px] md:scroll-m-0 md:scroll-p-[auto]">
            <button
              type="button"
              className="static text-[13.3333px] font-normal [align-items:normal] bg-zinc-100 caret-black inline-block shrink justify-normal tracking-[normal] leading-[normal] min-h-0 min-w-0 outline-black outline-0 text-center text-wrap align-baseline py-px rounded-none font-arial md:relative md:appearance-none md:text-2xl md:font-bold md:items-center md:aspect-auto md:bg-indigo-950 md:caret-transparent md:flex md:shrink-0 md:justify-center md:min-h-[auto] md:min-w-[auto] md:outline-slate-950 md:outline md:outline-4 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:align-middle md:[mask-position:0%] md:bg-left-top md:py-1.5 md:scroll-m-0 md:scroll-p-[auto] md:rounded-xl"
            >
              <div className="[align-items:normal] box-content caret-black block h-auto justify-normal min-h-0 min-w-0 text-wrap w-auto md:items-center md:aspect-auto md:box-border md:caret-transparent md:flex md:h-6 md:justify-center md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:w-6 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                <img
                  src="https://c.animaapp.com/mndr0fyp9c515x/assets/icon-24.svg"
                  alt="Icon"
                  className="box-content caret-black h-auto text-wrap align-middle w-auto md:aspect-auto md:box-border md:caret-transparent md:h-6 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:align-baseline md:w-6 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
                />
              </div>
            </button>
          </div>
          <SidebarNav />
        </div>
      </div>
      <div className="box-border caret-transparent grid col-end-auto col-start-auto row-end-auto row-start-auto [grid-template-areas:'nav''main''bottom'] grid-cols-[1fr] grid-rows-[56px_1fr_60px] h-full min-h-[auto] min-w-[auto] overflow-hidden md:col-end-[right] md:col-start-[right] md:row-end-[right] md:row-start-[right] md:[grid-template-areas:'nav_chat''main_chat'] md:grid-cols-[1fr_0px] md:grid-rows-[72px_1fr]">
        <div className="relative box-border caret-transparent col-end-[main] col-start-[main] row-end-[main] row-start-[main] min-h-[auto] min-w-[auto] overflow-clip before:accent-auto before:shadow-[rgb(25,25,57)_0px_0px_0px_16px] before:box-border before:caret-transparent before:text-white before:block before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[0.15008px] before:leading-6 before:list-outside before:list-disc before:pointer-events-none before:absolute before:text-start before:no-underline before:indent-[0px] before:normal-case before:visible before:rounded-tl-xl before:border-t-0 before:border-separate before:border-white before:inset-0 before:font-excon before:md:border-t-slate-950 before:md:border-t-4"></div>
        <header className="relative items-center bg-slate-800 box-border caret-transparent flex flex-col shrink-0 col-end-[nav] col-start-[nav] row-end-[nav] row-start-[nav] min-h-[auto] min-w-[auto] pointer-events-auto w-full z-auto right-0 top-0 md:z-[2]">
          <div className="items-center box-border caret-transparent flex h-full justify-center min-h-[auto] min-w-[auto] w-full">
            <div className="relative items-center box-border caret-transparent grid grid-cols-none h-14 justify-between max-w-[1248px] min-h-14 min-w-[auto] w-full px-4 md:grid-cols-[1fr_auto_1fr] md:h-[72px] md:px-6">
              <div className="items-center box-border caret-transparent flex col-end-2 col-start-1 h-full min-h-[auto] min-w-[auto] w-full">
                <a
                  title="Go Home"
                  href="/"
                  className="relative text-blue-700 box-border caret-transparent block shrink-0 h-9 min-h-[auto] min-w-[auto] underline w-9 overflow-hidden md:h-11 md:w-[170px] hover:text-blue-800 hover:bg-transparent hover:shadow-none hover:outline-offset-0 hover:outline-0 hover:underline hover:decoration-solid hover:decoration-auto hover:border-blue-700 hover:rounded-none hover:border-0 hover:border-none"
                >
                  <img
                    alt="Roobet"
                    src="https://c.animaapp.com/mndr0fyp9c515x/assets/r-NQNxh0.svg"
                    className="text-yellow-400 box-border caret-transparent inline-block h-full hover:text-yellow-500 hover:bg-transparent hover:shadow-none hover:outline-offset-0 hover:outline-0 hover:no-underline hover:decoration-solid hover:decoration-auto hover:border-yellow-400 hover:rounded-none hover:border-0 hover:border-none"
                  />
                </a>
              </div>
              <div className="items-center box-border caret-transparent gap-x-2 flex basis-[0%] grow col-start-3 justify-end min-h-[auto] min-w-[auto] gap-y-2 z-[2]">
                <button
                  type="button"
                  className="static text-[13.3333px] font-normal [align-items:normal] bg-zinc-100 caret-black inline-block shrink justify-normal tracking-[normal] leading-[normal] min-h-0 min-w-0 text-center align-baseline py-px rounded-none border-0 border-[currentcolor] font-arial md:relative md:appearance-none md:text-2xl md:font-bold md:items-center md:aspect-auto md:bg-indigo-950 md:caret-transparent md:flex md:shrink-0 md:justify-center md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-middle md:border-slate-950 md:[mask-position:0%] md:bg-left-top md:py-1.5 md:scroll-m-0 md:scroll-p-[auto] md:rounded-2xl md:border-4"
                >
                  <div className="[align-items:normal] box-content caret-black block h-auto justify-normal min-h-0 min-w-0 w-auto md:items-center md:aspect-auto md:box-border md:caret-transparent md:flex md:h-6 md:justify-center md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-6 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                    <img
                      src="https://c.animaapp.com/mndr0fyp9c515x/assets/icon-66.svg"
                      alt="Icon"
                      className="box-content caret-black h-auto align-middle w-auto md:aspect-auto md:box-border md:caret-transparent md:h-4 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-4 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
                    />
                  </div>
                </button>
                <div className="bg-slate-950 box-border caret-transparent gap-x-1 flex min-h-[auto] min-w-[auto] gap-y-1 p-1 rounded-2xl">
                  <button
                    type="button"
                    className="relative appearance-none text-sm font-bold items-center bg-indigo-950 caret-transparent flex justify-center tracking-[normal] leading-[24.5px] min-h-[auto] min-w-16 text-center align-middle pt-[9px] pb-[11px] px-3.5 rounded-xl hover:text-white hover:bg-indigo-950 hover:shadow-none hover:outline-offset-0 hover:outline-0 hover:no-underline hover:decoration-solid hover:decoration-auto hover:rounded-xl hover:border-0 hover:border-none hover:border-white"
                  >
                    <span className="relative text-xs box-border caret-transparent block leading-4 min-h-[auto] min-w-[auto] text-ellipsis text-nowrap overflow-hidden hover:text-white hover:bg-transparent hover:shadow-none hover:outline-offset-0 hover:outline-0 hover:no-underline hover:decoration-solid hover:decoration-auto hover:rounded-none hover:border-0 hover:border-none hover:border-white">
                      Login
                    </span>
                  </button>
                  <button
                    type="button"
                    className="relative appearance-none text-sm font-black items-center bg-transparent bg-[linear-gradient(420deg,rgb(255,206,0)_0%,rgb(255,206,0)_49%,rgb(255,184,0)_49%,rgb(255,184,0)_100%)] bg-no-repeat bg-size-[100%_100%] shadow-[rgb(197,106,24)_0px_-3px_0px_0px_inset,rgb(255,234,47)_0px_2px_0px_0px_inset] caret-transparent flex justify-center tracking-[normal] leading-[24.5px] min-h-[auto] min-w-16 text-center align-middle bg-[position:left_50%] pt-1.5 pb-2.5 px-3.5 rounded-xl before:accent-auto before:bg-white before:box-border before:caret-transparent before:text-white before:block before:text-sm before:not-italic before:normal-nums before:font-black before:h-0.5 before:tracking-[normal] before:leading-[24.5px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-center before:no-underline before:indent-[0px] before:normal-case before:visible before:w-[5px] before:rounded-2xl before:border-separate before:left-2.5 before:top-0 before:font-excon hover:text-white hover:bg-violet-600 hover:shadow-none hover:outline-offset-0 hover:outline-0 hover:no-underline hover:decoration-solid hover:decoration-auto hover:rounded-xl hover:border-0 hover:border-none hover:border-white"
                  >
                    <span className="relative text-xs box-border caret-transparent block leading-4 min-h-[auto] min-w-[auto] text-ellipsis text-nowrap overflow-hidden p-0.5 hover:text-white hover:bg-transparent hover:shadow-none hover:outline-offset-0 hover:outline-0 hover:no-underline hover:decoration-solid hover:decoration-auto hover:rounded-none hover:border-0 hover:border-none hover:border-white">
                      <span className="absolute box-border caret-transparent block text-nowrap left-0.5 hover:text-white hover:bg-transparent hover:shadow-none hover:outline-offset-0 hover:outline-0 hover:no-underline hover:decoration-solid hover:decoration-auto hover:rounded-none hover:border-0 hover:border-none hover:border-white">
                        Register
                      </span>
                      <span className="absolute box-border caret-transparent block text-nowrap left-0.5 top-[3px] hover:text-white hover:bg-transparent hover:shadow-none hover:outline-offset-0 hover:outline-0 hover:no-underline hover:decoration-solid hover:decoration-auto hover:rounded-none hover:border-0 hover:border-none hover:border-white">
                        Register
                      </span>
                      <span className="relative box-border caret-transparent text-nowrap hover:text-white hover:bg-transparent hover:shadow-none hover:outline-offset-0 hover:outline-0 hover:no-underline hover:decoration-solid hover:decoration-auto hover:rounded-none hover:border-0 hover:border-none hover:border-white">
                        Register
                      </span>
                    </span>
                  </button>
                </div>
                <button
                  type="button"
                  className="static text-[13.3333px] font-normal [align-items:normal] bg-zinc-100 caret-black inline-block shrink justify-normal tracking-[normal] leading-[normal] min-h-0 min-w-0 text-center align-baseline py-px rounded-none border-0 border-[currentcolor] font-arial md:relative md:appearance-none md:text-2xl md:font-bold md:items-center md:aspect-auto md:bg-indigo-950 md:caret-transparent md:flex md:shrink-0 md:justify-center md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-middle md:border-slate-950 md:[mask-position:0%] md:bg-left-top md:py-1.5 md:scroll-m-0 md:scroll-p-[auto] md:rounded-2xl md:border-4"
                >
                  <div className="[align-items:normal] box-content caret-black block h-auto justify-normal min-h-0 min-w-0 w-auto md:items-center md:aspect-auto md:box-border md:caret-transparent md:flex md:h-6 md:justify-center md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-6 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                    <img
                      src="https://c.animaapp.com/mndr0fyp9c515x/assets/icon-67.svg"
                      alt="Icon"
                      className="box-content caret-black h-auto align-middle w-auto md:aspect-auto md:box-border md:caret-transparent md:h-4 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-4 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
                    />
                  </div>
                </button>
              </div>
            </div>
          </div>
        </header>
        <div className="relative items-center self-end box-border caret-transparent flex col-end-[main] col-start-[main] row-end-[main] row-start-[main] justify-self-end min-h-[auto] min-w-[auto] pointer-events-auto mb-4 md:mb-12"></div>
        <div className="static box-content caret-black block flex-row shrink col-end-auto col-start-auto row-end-auto row-start-auto h-auto min-h-0 min-w-0 pointer-events-auto w-auto z-auto md:relative md:aspect-auto md:box-border md:caret-transparent md:flex md:flex-col md:shrink-0 md:col-end-[chat] md:col-start-[chat] md:row-end-[chat] md:row-start-[chat] md:h-full md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:z-0 md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
          <div className="static bg-transparent box-content caret-black min-h-0 min-w-0 md:relative md:aspect-auto md:bg-slate-950 md:box-border md:caret-transparent md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
            <div className="[align-items:normal] bg-transparent box-content caret-black block h-auto justify-normal border-l-0 border-black md:items-center md:aspect-auto md:bg-slate-800 md:border-l-violet-600 md:box-border md:caret-transparent md:flex md:h-[72px] md:justify-between md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:p-3.5 md:scroll-m-0 md:scroll-p-[auto] md:border-l-4 md:border-r-white md:border-y-white">
              <div className="bg-transparent box-content caret-black min-h-0 min-w-0 rounded-none md:aspect-auto md:bg-slate-950 md:box-border md:caret-transparent md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:p-1 md:scroll-m-0 md:scroll-p-[auto] md:rounded-2xl">
                <div className="static box-content caret-black w-auto md:relative md:aspect-auto md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-min md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                  <div className="static text-base [align-items:normal] bg-transparent box-content caret-black block tracking-[normal] leading-[normal] outline-black outline-offset-0 outline-0 w-auto rounded-none md:relative md:text-sm md:items-center md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:inline-flex md:tracking-[0.13132px] md:leading-[20.125px] md:outline-transparent md:-outline-offset-2 md:outline md:outline-2 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-fit md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-xl">
                    <div
                      role="combobox"
                      className="font-normal [align-items:normal] caret-black block leading-[normal] min-h-0 text-clip text-wrap w-auto p-0 rounded-none md:font-bold md:items-center md:aspect-auto md:caret-transparent md:flex md:leading-6 md:min-h-6 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:w-full md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:pl-2 md:pr-[37px] md:py-1.5 md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"
                    >
                      <div className="caret-black gap-x-[normal] block min-h-0 min-w-0 gap-y-[normal] text-wrap md:aspect-auto md:caret-transparent md:gap-x-2 md:flex md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                        <img
                          src="https://c.animaapp.com/mndr0fyp9c515x/assets/icon-22.svg"
                          alt="Icon"
                          className="caret-black h-auto text-wrap align-middle w-auto md:aspect-auto md:caret-transparent md:h-5 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:align-baseline md:w-5 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
                        />
                        <p className="caret-black tracking-[normal] leading-[normal] max-w-none min-h-0 min-w-0 text-clip text-wrap w-auto md:aspect-auto md:caret-transparent md:leading-5 md:max-w-[63px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:w-fit md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                          English
                        </p>
                      </div>
                    </div>
                    <input
                      value="en"
                      className="static text-black text-[13.3333px] box-content caret-black inline-block tracking-[normal] leading-[normal] opacity-100 pointer-events-auto w-auto left-auto bottom-auto font-arial md:absolute md:aspect-auto md:box-border md:caret-transparent md:block md:opacity-0 md:overscroll-x-auto md:overscroll-y-auto md:pointer-events-none md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:left-0 md:bottom-0"
                    />
                    <span className="static text-black text-base [align-items:normal] box-content caret-black inline shrink h-auto justify-normal pointer-events-auto text-start w-auto rounded-none right-auto top-auto md:absolute md:text-black/50 md:text-2xl md:items-center md:aspect-auto md:box-border md:caret-transparent md:flex md:shrink-0 md:h-6 md:justify-center md:overscroll-x-auto md:overscroll-y-auto md:pointer-events-none md:snap-align-none md:snap-normal md:snap-none md:text-center md:decoration-auto md:underline-offset-auto md:top-[calc(50%_-_12px)] md:w-6 md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg md:right-1.5">
                      <img
                        src="https://c.animaapp.com/mndr0fyp9c515x/assets/icon-23.svg"
                        alt="Icon"
                        className="box-content caret-black h-auto align-middle w-auto md:aspect-auto md:box-border md:caret-transparent md:h-6 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-6 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
                      />
                    </span>
                    <fieldset className="static box-content caret-black block min-w-min pointer-events-auto text-start pt-[5.6px] pb-2.5 px-3 rounded-none inset-auto md:absolute md:aspect-auto md:box-border md:caret-transparent md:hidden md:min-w-[0%] md:overscroll-x-auto md:overscroll-y-auto md:pointer-events-none md:snap-align-none md:snap-normal md:snap-none md:text-left md:decoration-auto md:underline-offset-auto md:top-[-5px] md:border md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:px-2 md:py-0 md:scroll-m-0 md:scroll-p-[auto] md:rounded-xl md:border-solid md:border-black/20 md:bottom-0 md:inset-x-0">
                      <legend className="box-content caret-black leading-[normal] px-0.5 md:aspect-auto md:box-border md:caret-transparent md:leading-[11px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:px-0 md:scroll-m-0 md:scroll-p-[auto]">
                        <span className="box-content caret-black md:aspect-auto md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                          ​
                        </span>
                      </legend>
                    </fieldset>
                  </div>
                </div>
              </div>
              <div className="box-content caret-black gap-x-[normal] block min-h-0 min-w-0 gap-y-[normal] ml-0 md:aspect-auto md:box-border md:caret-transparent md:gap-x-2 md:flex md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:ml-auto md:scroll-m-0 md:scroll-p-[auto]">
                <button
                  type="button"
                  className="static text-[13.3333px] font-normal [align-items:normal] bg-zinc-100 caret-black inline-block shrink justify-normal tracking-[normal] leading-[normal] min-h-0 min-w-0 text-center align-baseline py-px rounded-none border-0 border-[currentcolor] font-arial md:relative md:appearance-none md:text-2xl md:font-bold md:items-center md:aspect-auto md:bg-indigo-950 md:caret-transparent md:flex md:shrink-0 md:justify-center md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-middle md:border-slate-950 md:[mask-position:0%] md:bg-left-top md:py-1.5 md:scroll-m-0 md:scroll-p-[auto] md:rounded-2xl md:border-4"
                >
                  <div className="[align-items:normal] box-content caret-black block h-auto justify-normal min-h-0 min-w-0 w-auto md:items-center md:aspect-auto md:box-border md:caret-transparent md:flex md:h-6 md:justify-center md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-6 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                    <img
                      src="https://c.animaapp.com/mndr0fyp9c515x/assets/icon-68.svg"
                      alt="Icon"
                      className="box-content caret-black h-auto align-middle w-auto md:aspect-auto md:box-border md:caret-transparent md:h-6 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-6 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
                    />
                  </div>
                </button>
                <button
                  type="button"
                  className="static text-[13.3333px] font-normal [align-items:normal] bg-zinc-100 caret-black inline-block shrink justify-normal tracking-[normal] leading-[normal] min-h-0 min-w-0 text-center align-baseline py-px rounded-none border-0 border-[currentcolor] font-arial md:relative md:appearance-none md:text-2xl md:font-bold md:items-center md:aspect-auto md:bg-indigo-950 md:caret-transparent md:flex md:shrink-0 md:justify-center md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-middle md:border-slate-950 md:[mask-position:0%] md:bg-left-top md:py-1.5 md:scroll-m-0 md:scroll-p-[auto] md:rounded-2xl md:border-4"
                >
                  <div className="[align-items:normal] box-content caret-black block h-auto justify-normal min-h-0 min-w-0 w-auto md:items-center md:aspect-auto md:box-border md:caret-transparent md:flex md:h-6 md:justify-center md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-6 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                    <img
                      src="https://c.animaapp.com/mndr0fyp9c515x/assets/icon-69.svg"
                      alt="Icon"
                      className="box-content caret-black h-auto align-middle w-auto md:aspect-auto md:box-border md:caret-transparent md:h-6 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-6 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
                    />
                  </div>
                </button>
              </div>
            </div>
            <div className="[align-items:normal] bg-transparent box-content caret-black block flex-nowrap px-0 md:items-center md:aspect-auto md:bg-slate-950 md:box-border md:caret-transparent md:flex md:flex-wrap md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:px-4 md:scroll-m-0 md:scroll-p-[auto]"></div>
            <div className="static bg-none box-content caret-black block h-auto w-auto z-auto border-t-0 border-black bottom-auto md:absolute md:aspect-auto md:bg-[linear-gradient(0deg,rgba(25,25,57,0)_0%,rgb(25,25,57)_100%)] md:border-t-slate-950 md:box-border md:caret-transparent md:flex md:h-5 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:z-10 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:border-t-4 md:border-b-white md:border-x-white md:-bottom-5"></div>
          </div>
          <div className="static box-content caret-black block basis-auto flex-row grow-0 min-h-0 min-w-0 md:relative md:aspect-auto md:box-border md:caret-transparent md:flex md:basis-[0%] md:flex-col md:grow md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
            <div className="bg-transparent box-content caret-black gap-x-[normal] block flex-row h-auto min-h-0 min-w-0 gap-y-[normal] pt-0 px-0 md:aspect-auto md:bg-slate-800 md:box-border md:caret-transparent md:gap-x-2 md:flex md:flex-col-reverse md:h-full md:min-h-[auto] md:min-w-[auto] md:overscroll-x-contain md:overscroll-y-contain md:gap-y-2 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:pt-2 md:px-4 md:scroll-m-0 md:scroll-p-[auto]">
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-14 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-[122px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-14 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-[122px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-14 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-[122px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-14 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-[122px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-14 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-[122px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-14 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-[122px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-14 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-[122px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-14 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-[122px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
              <span className="bg-transparent box-content caret-black inline shrink h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:block md:shrink-0 md:h-9 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"></span>
            </div>
            <div className="bg-transparent box-content caret-black shrink min-h-0 min-w-0 p-0 md:aspect-auto md:bg-slate-800 md:box-border md:caret-transparent md:shrink-0 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:pt-2 md:pb-4 md:px-4 md:scroll-m-0 md:scroll-p-[auto]">
              <div className="[align-items:normal] box-content caret-black gap-x-[normal] block gap-y-[normal] my-0 md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-2 md:flex md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:my-2 md:scroll-m-0 md:scroll-p-[auto]">
                <div className="box-content caret-black basis-auto grow-0 min-h-0 min-w-0 md:aspect-auto md:box-border md:caret-transparent md:basis-[0%] md:grow md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                  <div className="[align-items:normal] box-content caret-black block flex-row w-auto md:items-baseline md:aspect-auto md:box-border md:caret-transparent md:flex md:flex-col md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                    <div className="static text-base [align-items:normal] bg-transparent box-content caret-black block tracking-[normal] leading-[normal] min-h-0 min-w-0 outline-black outline-offset-0 outline-0 w-auto rounded-none md:relative md:text-sm md:items-center md:aspect-auto md:bg-slate-950 md:box-border md:caret-transparent md:flex md:tracking-[0.13132px] md:leading-[20.125px] md:min-h-[auto] md:min-w-[auto] md:outline-indigo-950 md:-outline-offset-2 md:outline md:outline-2 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-xl">
                      <input
                        placeholder="Enter a message"
                        type="text"
                        value=""
                        className="text-[13.3333px] font-normal bg-white caret-black inline-block leading-[normal] min-h-0 w-auto px-0.5 py-px md:text-[13px] md:font-medium md:aspect-auto md:bg-transparent md:caret-transparent md:block md:leading-6 md:min-h-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:px-2.5 md:py-2 md:scroll-m-0 md:scroll-p-[auto]"
                      />
                      <fieldset className="static box-content caret-black block min-w-min pointer-events-auto text-start pt-[5.6px] pb-2.5 px-3 rounded-none inset-auto md:absolute md:aspect-auto md:box-border md:caret-transparent md:hidden md:min-w-[0%] md:overscroll-x-auto md:overscroll-y-auto md:pointer-events-none md:snap-align-none md:snap-normal md:snap-none md:text-left md:decoration-auto md:underline-offset-auto md:top-[-5px] md:border md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:px-2 md:py-0 md:scroll-m-0 md:scroll-p-[auto] md:rounded-xl md:border-solid md:border-black/20 md:bottom-0 md:inset-x-0">
                        <legend className="box-content caret-black leading-[normal] px-0.5 md:aspect-auto md:box-border md:caret-transparent md:leading-[11px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:px-0 md:scroll-m-0 md:scroll-p-[auto]">
                          <span className="box-content caret-black md:aspect-auto md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                            ​
                          </span>
                        </legend>
                      </fieldset>
                    </div>
                  </div>
                </div>
                <button
                  type="button"
                  className="static text-[13.3333px] font-normal [align-items:normal] bg-zinc-100 caret-black inline-block shrink justify-normal tracking-[normal] leading-[normal] min-h-0 min-w-0 text-center align-baseline rounded-none font-arial md:relative md:appearance-none md:text-[28px] md:font-bold md:items-center md:aspect-auto md:bg-indigo-950 md:caret-transparent md:flex md:shrink-0 md:justify-center md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-middle md:[mask-position:0%] md:bg-left-top md:p-2 md:scroll-m-0 md:scroll-p-[auto] md:rounded-xl"
                >
                  <div className="[align-items:normal] box-content caret-black block h-auto justify-normal min-h-0 min-w-0 w-auto md:items-center md:aspect-auto md:box-border md:caret-transparent md:flex md:h-6 md:justify-center md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-6 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                    <img
                      alt="Send"
                      src="https://c.animaapp.com/mndr0fyp9c515x/assets/image-25.svg"
                      className="box-content caret-black min-h-0 min-w-0 align-middle md:aspect-auto md:box-border md:caret-transparent md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
                    />
                  </div>
                </button>
              </div>
              <div className="text-base [align-items:normal] box-content caret-black gap-x-[normal] block gap-y-[normal] md:text-xs md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-2 md:flex md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                <button
                  type="button"
                  className="static text-black text-[13.3333px] font-normal [align-items:normal] bg-zinc-100 caret-black inline-block justify-normal tracking-[normal] leading-[normal] min-h-0 min-w-0 text-center align-baseline rounded-none md:relative md:appearance-none md:text-slate-400 md:text-[13px] md:font-bold md:items-center md:aspect-auto md:bg-transparent md:caret-transparent md:flex md:justify-center md:leading-[22.75px] md:min-h-[auto] md:min-w-[26px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-middle md:[mask-position:0%] md:bg-left-top md:p-0 md:scroll-m-0 md:scroll-p-[auto] md:rounded-xl"
                >
                  <span className="static text-base box-content caret-black inline leading-[normal] min-h-0 min-w-0 text-clip text-wrap md:relative md:text-xs md:aspect-auto md:box-border md:caret-transparent md:block md:leading-4 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                    Rain
                  </span>
                </button>
                <button
                  type="button"
                  className="static text-black text-[13.3333px] font-normal [align-items:normal] bg-zinc-100 caret-black inline-block justify-normal tracking-[normal] leading-[normal] min-h-0 min-w-0 text-center align-baseline rounded-none md:relative md:appearance-none md:text-slate-400 md:text-[13px] md:font-bold md:items-center md:aspect-auto md:bg-transparent md:caret-transparent md:flex md:justify-center md:leading-[22.75px] md:min-h-[auto] md:min-w-[26px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-middle md:[mask-position:0%] md:bg-left-top md:p-0 md:scroll-m-0 md:scroll-p-[auto] md:rounded-xl"
                >
                  <span className="static text-base box-content caret-black inline leading-[normal] min-h-0 min-w-0 text-clip text-wrap md:relative md:text-xs md:aspect-auto md:box-border md:caret-transparent md:block md:leading-4 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                    Chat Rules
                  </span>
                </button>
                <span className="text-black font-normal box-content caret-black inline basis-auto grow-0 tracking-[normal] leading-[normal] min-h-0 min-w-0 text-start md:text-indigo-900 md:font-medium md:aspect-auto md:box-border md:caret-transparent md:block md:basis-[0%] md:grow md:leading-4 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:text-right md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                  0/120
                </span>
              </div>
              <div className="box-content caret-black shrink md:aspect-auto md:box-border md:caret-transparent md:shrink-0 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                <div className="static bg-transparent box-content caret-black block flex-row grow-0 shrink max-h-none transform-none visible z-auto rounded-t-none bottom-auto inset-x-auto md:absolute md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:flex md:flex-col md:grow md:shrink-0 md:max-h-full md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:translate-y-[310px] md:invisible md:z-[1200] md:overflow-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-t-xl md:bottom-0 md:inset-x-0">
                  <div className="[align-items:normal] self-auto bg-transparent box-content caret-black gap-x-[normal] block h-auto min-h-0 min-w-0 gap-y-[normal] p-0 md:items-center md:self-stretch md:aspect-auto md:bg-slate-950 md:box-border md:caret-transparent md:gap-x-3 md:flex md:h-10 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-3 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:pl-4 md:pr-2 md:py-3 md:scroll-m-0 md:scroll-p-[auto]">
                    <span className="text-base font-normal box-content caret-black inline tracking-[normal] leading-[normal] min-h-0 min-w-0 md:text-xs md:font-bold md:aspect-auto md:box-border md:caret-transparent md:block md:leading-4 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                      Start Rain
                    </span>
                    <div className="box-content caret-black min-h-0 min-w-0 ml-0 md:aspect-auto md:box-border md:caret-transparent md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:ml-auto md:scroll-m-0 md:scroll-p-[auto]">
                      <button
                        type="button"
                        className="static text-[13.3333px] font-normal [align-items:normal] bg-zinc-100 caret-black inline-block shrink h-auto justify-normal tracking-[normal] leading-[normal] text-center align-baseline w-auto rounded-none font-arial md:relative md:appearance-none md:text-2xl md:font-bold md:items-center md:aspect-auto md:bg-transparent md:caret-transparent md:flex md:shrink-0 md:h-6 md:justify-center md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-middle md:w-6 md:[mask-position:0%] md:bg-left-top md:p-0 md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"
                      >
                        <img
                          src="https://c.animaapp.com/mndr0fyp9c515x/assets/icon-70.svg"
                          alt="Icon"
                          className="box-content caret-black h-auto align-middle w-auto md:aspect-auto md:box-border md:caret-transparent md:h-6 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-6 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
                        />
                      </button>
                    </div>
                  </div>
                  <form className="box-content caret-black block flex-row min-h-0 min-w-0 md:aspect-auto md:box-border md:caret-transparent md:flex md:flex-col md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                    <div className="bg-transparent box-content caret-black gap-x-[normal] block flex-row min-h-0 min-w-0 gap-y-[normal] rounded-none md:aspect-auto md:bg-slate-800 md:box-border md:caret-transparent md:gap-x-3 md:flex md:flex-col md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-3 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:m-4 md:p-4 md:scroll-m-0 md:scroll-p-[auto] md:rounded-xl">
                      <div className="[align-items:normal] box-content caret-black block flex-row min-h-0 min-w-0 w-auto md:items-baseline md:aspect-auto md:box-border md:caret-transparent md:flex md:flex-col md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                        <label className="text-black text-base font-normal box-content caret-black gap-x-[normal] inline tracking-[normal] leading-[normal] max-w-none min-h-0 min-w-0 gap-y-[normal] text-clip text-wrap origin-[50%_50%] mb-0 md:text-slate-400 md:text-sm md:font-medium md:aspect-auto md:box-border md:caret-transparent md:gap-x-4 md:block md:leading-5 md:max-w-full md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-4 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:origin-[0%_0%] md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:mb-1.5 md:scroll-m-0 md:scroll-p-[auto]">
                          Amount
                        </label>
                        <div className="static [align-items:normal] bg-transparent box-content caret-black block leading-[normal] min-h-0 min-w-0 outline-black outline-offset-0 outline-0 w-auto pl-0 rounded-none md:relative md:items-center md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:flex md:leading-[23px] md:min-h-[auto] md:min-w-[auto] md:outline-indigo-900 md:-outline-offset-2 md:outline md:outline-2 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:pl-3 md:scroll-m-0 md:scroll-p-[auto] md:rounded-xl">
                          <div className="text-black [align-items:normal] box-content caret-black block h-auto max-h-none min-h-0 min-w-0 text-wrap mr-0 md:text-indigo-300 md:items-center md:aspect-auto md:box-border md:caret-transparent md:flex md:h-[0.16px] md:max-h-8 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:mr-2 md:scroll-m-0 md:scroll-p-[auto]">
                            <span className="box-content caret-black inline min-h-0 min-w-0 text-wrap md:aspect-auto md:box-border md:caret-transparent md:block md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                              ​
                            </span>
                            $
                          </div>
                          <input
                            type="number"
                            value="2"
                            name="amount"
                            className="bg-white caret-black inline-block leading-[normal] min-h-0 w-auto px-0.5 py-px md:aspect-auto md:bg-transparent md:caret-transparent md:block md:leading-6 md:min-h-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:pl-0 md:pr-3 md:py-2.5 md:scroll-m-0 md:scroll-p-[auto]"
                          />
                          <fieldset className="static box-content caret-black block min-w-min pointer-events-auto text-start pt-[5.6px] pb-2.5 px-3 rounded-none inset-auto md:absolute md:aspect-auto md:box-border md:caret-transparent md:hidden md:min-w-[0%] md:overscroll-x-auto md:overscroll-y-auto md:pointer-events-none md:snap-align-none md:snap-normal md:snap-none md:text-left md:decoration-auto md:underline-offset-auto md:top-[-5px] md:border md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:px-2 md:py-0 md:scroll-m-0 md:scroll-p-[auto] md:rounded-xl md:border-solid md:border-black/20 md:bottom-0 md:inset-x-0">
                            <legend className="box-content caret-black leading-[normal] px-0.5 md:aspect-auto md:box-border md:caret-transparent md:leading-[11px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:px-0 md:scroll-m-0 md:scroll-p-[auto]">
                              <span className="box-content caret-black md:aspect-auto md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                ​
                              </span>
                            </legend>
                          </fieldset>
                        </div>
                        <p className="text-black text-base font-normal box-content caret-black tracking-[normal] leading-[normal] min-h-0 min-w-0 text-start w-auto mt-0 md:text-slate-400 md:text-xs md:font-medium md:aspect-auto md:box-border md:caret-transparent md:tracking-[0.39996px] md:leading-[19.92px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:text-left md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:mt-2 md:scroll-m-0 md:scroll-p-[auto]">
                          <p className="box-content caret-black tracking-[normal] leading-[normal] w-auto md:aspect-auto md:box-border md:caret-transparent md:leading-4 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                            $2.00 Minimum Amount
                          </p>
                        </p>
                      </div>
                    </div>
                    <div className="[align-items:normal] self-auto bg-transparent box-content caret-black gap-x-[normal] block flex-row min-h-0 min-w-0 gap-y-[normal] md:items-center md:self-stretch md:aspect-auto md:bg-slate-950 md:box-border md:caret-transparent md:gap-x-3 md:flex md:flex-col md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-3 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:p-4 md:scroll-m-0 md:scroll-p-[auto]">
                      <button
                        type="submit"
                        className="static text-[13.3333px] font-normal [align-items:normal] bg-zinc-100 bg-none bg-repeat bg-auto shadow-none caret-black inline-block justify-normal tracking-[normal] leading-[normal] min-h-0 min-w-0 text-center align-baseline w-auto px-1.5 py-px rounded-none md:relative md:appearance-none md:text-sm md:font-black md:items-center md:aspect-auto md:bg-transparent md:bg-[linear-gradient(420deg,rgb(255,206,0)_0%,rgb(255,206,0)_15%,rgb(255,184,0)_15%,rgb(255,184,0)_100%)] md:bg-no-repeat md:bg-size-[100%_100%] md:shadow-[rgb(197,106,24)_0px_-3px_0px_0px_inset,rgb(255,234,47)_0px_2px_0px_0px_inset] md:caret-transparent md:flex md:justify-center md:leading-[24.5px] md:min-h-[auto] md:min-w-16 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-middle md:w-full md:[mask-position:0%] md:bg-left md:pt-2.5 md:pb-3.5 md:px-3.5 md:scroll-m-0 md:scroll-p-[auto] md:rounded-xl before:md:accent-auto before:md:bg-white before:md:box-border before:md:caret-transparent before:md:text-white before:md:block before:md:text-sm before:md:not-italic before:md:normal-nums before:md:font-black before:md:h-0.5 before:md:tracking-[normal] before:md:leading-[24.5px] before:md:list-outside before:md:list-disc before:md:pointer-events-auto before:md:absolute before:md:text-center before:md:no-underline before:md:indent-[0px] before:md:normal-case before:md:invisible before:md:w-[5px] before:md:rounded-2xl before:md:border-separate before:md:left-2.5 before:md:top-0 before:md:font-excon"
                      >
                        <span className="static box-content caret-black inline leading-[normal] min-h-0 min-w-0 text-clip text-wrap visible md:relative md:aspect-auto md:box-border md:caret-transparent md:block md:leading-5 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:p-0.5 md:scroll-m-0 md:scroll-p-[auto]">
                          <span className="static box-content caret-black inline text-wrap left-auto md:absolute md:aspect-auto md:box-border md:caret-transparent md:block md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:left-0.5">
                            Start Rain
                          </span>
                          <span className="static box-content caret-black inline text-wrap left-auto top-auto md:absolute md:aspect-auto md:box-border md:caret-transparent md:block md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:left-0.5 md:top-[3px]">
                            Start Rain
                          </span>
                          <span className="static box-content caret-black text-wrap md:relative md:aspect-auto md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                            Start Rain
                          </span>
                        </span>
                      </button>
                    </div>
                  </form>
                </div>
              </div>
              <div className="box-content caret-black shrink md:aspect-auto md:box-border md:caret-transparent md:shrink-0 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                <div className="static bg-transparent box-content caret-black block flex-row grow-0 shrink max-h-none transform-none visible z-auto rounded-t-none bottom-auto inset-x-auto md:absolute md:aspect-auto md:bg-indigo-950 md:box-border md:caret-transparent md:flex md:flex-col md:grow md:shrink-0 md:max-h-full md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:translate-y-[816.828px] md:invisible md:z-[1200] md:overflow-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-t-xl md:bottom-0 md:inset-x-0">
                  <div className="[align-items:normal] self-auto bg-transparent box-content caret-black gap-x-[normal] block h-auto min-h-0 min-w-0 gap-y-[normal] p-0 md:items-center md:self-stretch md:aspect-auto md:bg-slate-950 md:box-border md:caret-transparent md:gap-x-3 md:flex md:h-10 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-3 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:pl-4 md:pr-2 md:py-3 md:scroll-m-0 md:scroll-p-[auto]">
                    <span className="text-base font-normal box-content caret-black inline tracking-[normal] leading-[normal] min-h-0 min-w-0 md:text-xs md:font-bold md:aspect-auto md:box-border md:caret-transparent md:block md:leading-4 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                      Chat Rules
                    </span>
                    <div className="box-content caret-black min-h-0 min-w-0 ml-0 md:aspect-auto md:box-border md:caret-transparent md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:ml-auto md:scroll-m-0 md:scroll-p-[auto]">
                      <button
                        type="button"
                        className="static text-[13.3333px] font-normal [align-items:normal] bg-zinc-100 caret-black inline-block shrink h-auto justify-normal tracking-[normal] leading-[normal] text-center align-baseline w-auto rounded-none font-arial md:relative md:appearance-none md:text-2xl md:font-bold md:items-center md:aspect-auto md:bg-transparent md:caret-transparent md:flex md:shrink-0 md:h-6 md:justify-center md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-middle md:w-6 md:[mask-position:0%] md:bg-left-top md:p-0 md:scroll-m-0 md:scroll-p-[auto] md:rounded-lg"
                      >
                        <img
                          src="https://c.animaapp.com/mndr0fyp9c515x/assets/icon-70.svg"
                          alt="Icon"
                          className="box-content caret-black h-auto align-middle w-auto md:aspect-auto md:box-border md:caret-transparent md:h-6 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-6 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
                        />
                      </button>
                    </div>
                  </div>
                  <div className="box-content caret-black block flex-row min-h-0 min-w-0 md:aspect-auto md:box-border md:caret-transparent md:flex md:flex-col md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:p-4 md:scroll-m-0 md:scroll-p-[auto]">
                    <ul className="box-content caret-black min-h-0 min-w-0 ml-0 pl-10 md:aspect-auto md:box-border md:caret-transparent md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:ml-4 md:pl-0 md:scroll-m-0 md:scroll-p-[auto]">
                      <li className="text-black text-base font-normal box-content caret-black leading-[normal] md:text-violet-200 md:text-xs md:font-medium md:aspect-auto md:box-border md:caret-transparent md:leading-[17.04px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                        <span className="box-content caret-black tracking-[normal] leading-[normal] md:aspect-auto md:box-border md:caret-transparent md:leading-4 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                          No spamming
                        </span>
                      </li>
                      <li className="text-black text-base font-normal box-content caret-black leading-[normal] md:text-violet-200 md:text-xs md:font-medium md:aspect-auto md:box-border md:caret-transparent md:leading-[17.04px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                        <span className="box-content caret-black tracking-[normal] leading-[normal] md:aspect-auto md:box-border md:caret-transparent md:leading-4 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                          No begging (Includes asking for rains)
                        </span>
                      </li>
                      <li className="text-black text-base font-normal box-content caret-black leading-[normal] md:text-violet-200 md:text-xs md:font-medium md:aspect-auto md:box-border md:caret-transparent md:leading-[17.04px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                        <span className="box-content caret-black tracking-[normal] leading-[normal] md:aspect-auto md:box-border md:caret-transparent md:leading-4 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                          No advertising
                        </span>
                      </li>
                      <li className="text-black text-base font-normal box-content caret-black leading-[normal] md:text-violet-200 md:text-xs md:font-medium md:aspect-auto md:box-border md:caret-transparent md:leading-[17.04px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                        <span className="box-content caret-black tracking-[normal] leading-[normal] md:aspect-auto md:box-border md:caret-transparent md:leading-4 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                          Zero tolerance for harassment (including racism,
                          sexism, and other hate speech)
                        </span>
                      </li>
                      <li className="text-black text-base font-normal box-content caret-black leading-[normal] md:text-violet-200 md:text-xs md:font-medium md:aspect-auto md:box-border md:caret-transparent md:leading-[17.04px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                        <span className="box-content caret-black tracking-[normal] leading-[normal] md:aspect-auto md:box-border md:caret-transparent md:leading-4 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                          No slandering website, staff, or other players
                        </span>
                      </li>
                      <li className="text-black text-base font-normal box-content caret-black leading-[normal] md:text-violet-200 md:text-xs md:font-medium md:aspect-auto md:box-border md:caret-transparent md:leading-[17.04px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                        <span className="box-content caret-black tracking-[normal] leading-[normal] md:aspect-auto md:box-border md:caret-transparent md:leading-4 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                          No sharing of socials or personal info
                        </span>
                      </li>
                      <li className="text-black text-base font-normal box-content caret-black leading-[normal] md:text-violet-200 md:text-xs md:font-medium md:aspect-auto md:box-border md:caret-transparent md:leading-[17.04px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                        <span className="box-content caret-black tracking-[normal] leading-[normal] md:aspect-auto md:box-border md:caret-transparent md:leading-4 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                          No posting external links
                        </span>
                      </li>
                    </ul>
                  </div>
                  <div className="[align-items:normal] self-auto bg-transparent box-content caret-black gap-x-[normal] block flex-row min-h-0 min-w-0 gap-y-[normal] md:items-center md:self-stretch md:aspect-auto md:bg-slate-950 md:box-border md:caret-transparent md:gap-x-3 md:flex md:flex-col md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-3 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:p-4 md:scroll-m-0 md:scroll-p-[auto]">
                    <button
                      type="button"
                      className="static text-[13.3333px] font-normal [align-items:normal] bg-zinc-100 bg-none bg-repeat bg-auto shadow-none caret-black inline-block justify-normal tracking-[normal] leading-[normal] min-h-0 min-w-0 text-center align-baseline w-auto px-1.5 py-px rounded-none md:relative md:appearance-none md:text-sm md:font-black md:items-center md:aspect-auto md:bg-transparent md:bg-[linear-gradient(420deg,rgb(255,206,0)_0%,rgb(255,206,0)_15%,rgb(255,184,0)_15%,rgb(255,184,0)_100%)] md:bg-no-repeat md:bg-size-[100%_100%] md:shadow-[rgb(197,106,24)_0px_-3px_0px_0px_inset,rgb(255,234,47)_0px_2px_0px_0px_inset] md:caret-transparent md:flex md:justify-center md:leading-[24.5px] md:min-h-[auto] md:min-w-16 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-middle md:w-full md:[mask-position:0%] md:bg-left md:pt-2.5 md:pb-3.5 md:px-3.5 md:scroll-m-0 md:scroll-p-[auto] md:rounded-xl before:md:accent-auto before:md:bg-white before:md:box-border before:md:caret-transparent before:md:text-white before:md:block before:md:text-sm before:md:not-italic before:md:normal-nums before:md:font-black before:md:h-0.5 before:md:tracking-[normal] before:md:leading-[24.5px] before:md:list-outside before:md:list-disc before:md:pointer-events-auto before:md:absolute before:md:text-center before:md:no-underline before:md:indent-[0px] before:md:normal-case before:md:invisible before:md:w-[5px] before:md:rounded-2xl before:md:border-separate before:md:left-2.5 before:md:top-0 before:md:font-excon"
                    >
                      <span className="static box-content caret-black inline leading-[normal] min-h-0 min-w-0 text-clip text-wrap visible md:relative md:aspect-auto md:box-border md:caret-transparent md:block md:leading-5 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:p-0.5 md:scroll-m-0 md:scroll-p-[auto]">
                        <span className="static box-content caret-black inline text-wrap left-auto md:absolute md:aspect-auto md:box-border md:caret-transparent md:block md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:left-0.5">
                          Got It
                        </span>
                        <span className="static box-content caret-black inline text-wrap left-auto top-auto md:absolute md:aspect-auto md:box-border md:caret-transparent md:block md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:left-0.5 md:top-[3px]">
                          Got It
                        </span>
                        <span className="static box-content caret-black text-wrap md:relative md:aspect-auto md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                          Got It
                        </span>
                      </span>
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
